api:
  port: :8080
logger:
  level: debug
services:
  seer:
    timeout: 5s
    max_retry: 1
    max_idle_cons_per_host: 1
    max_idle_cons: 1
    max_cons_per_host: 1
    url: http://127.0.0.1:8000
    enable: true